name: PR Codex Auto Comment

on:
  pull_request_target:
    types: [opened]  # PR作成時に1回だけ

permissions:
  # 最小権限（コメント投稿に必要）
  issues: write
  pull-requests: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for permissions to propagate
        run: sleep 25

      - name: Post "@Codex review" comment
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: "@Codex review"
            });
