name: Request Codex review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codex-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Post @codex review as a connected user
        env:
          GH_TOKEN: ${{ secrets.CODEX_COMMENT_TOKEN }} # ← Codex連携済みユーザーのPAT
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          gh api \
            -X POST \
            /repos/$REPO/issues/$PR_NUMBER/comments \
            -f body='@codex review'
